#!/bin/bash
apt-get update
wget http://nginx.org/download/nginx-1.7.8.tar.gz
tar -xf nginx-1.7.8.tar.gz
apt-get install git
git clone https://github.com/cuber/ngx_http_google_filter_module
 git clone https://github.com/yaoweibin/ngx_http_substitutions_filter_modul
apt-get install libpcre3 libpcre3-dev
apt-get install openssl libssl-devlibssl-dev
cd /root/nginx-1.7.8
./configure --prefix=/usr/local/nginx-1.7.8 --add-module=/root/ngx_http_google_filter_module --add-module=/root/ngx_http_substitutions_filter_module --with-http_ssl_module
make & make install


